version: '3'
services:
  app:
    image: "ruimo/fs:${TAG_NAME:-latest}"
    environment:
     - APP_SECRET
     - POSTGRES_SU_PASSWORD
     - CONF_FILE
    ports:
     - "$PUBLISH_PORT:9000"
    restart: always
  db:
    image: "postgres:11"
    environment:
     - POSTGRES_SU_PASSWORD
    volumes:
     - /var/fs:/var/lib/postgresql/data
    restart: always
